### ISSUE TITLE
AFL Live Games and Replays not playing - 'Connection Aborted' error

### ISSUE THREAD

**Issue by chchyeah** [aussieaddons/repo#71] opened 2018-04-07 07:55 UTC
Running Kodi on Raspberry Pi. AFL add on installed and working for some videos, such as press conferences and highlights.

However, when I select a game replay or live game, after authenticating it just hangs - it will not play games.

This problem started towards the end of last season. I have removed other addons and also removed the AFL add on and tried to re-add. Problem persists.

Any ideas?

Thanks

**Comment by andybotting** [comment] 2018-04-07 08:08
First step is to send us an issue report. You can do this from the debug
menu from the add-on settings.

Let me know what ID it gives you (the last few numbers of the url).

Cheers

**Comment by chchyeah** [comment] 2018-04-07 21:35
I just tried to replay yesterday's game and after leaving it for a long time, received this error message: 

play.py(40) - AussieAddonsException Error: HTTPSConnectionPool(host='api.afl.com.au',port=443): Max retires exceeded with url:
/cfs/users/mis-uuid-40156a5d9525890ea31fcacba894bd4b/t

**Comment by chchyeah** [comment] 2018-04-08 03:25
@andybotting Any thoughts on this one Andy? Really strange that it only happens for live games and some replays.

**Comment by andybotting** [comment] 2018-04-08 03:46
Hey. Just had a quick look at your log, and the first thing that jumps out at me is that you've running Kodi v15.  We've seen issues with older versions, so I'd recommend you upgrade to the latest version of OpenELEC. You're running v6 - I think the latest is v8-something.

**Comment by chchyeah** [comment] 2018-04-13 22:58
Thanks Andy - I have blown up my Pi and re-installed with v17. Problem is still happening.

I logged another error report - 2568. Any ideas would be appreciated. Thanks

**Comment by glennguy** [comment] 2018-04-14 00:31
Hey @chchyeah could you reboot your pi, recreate the problem and submit a new log? The log in 2568 is massive and has been truncated during the upload so we can't see the errors from the add-on.

**Comment by chchyeah** [comment] 2018-04-14 01:09
Thanks. I did this. New error report: 2570

**Comment by glennguy** [comment] 2018-04-14 03:09
@chchyeah had a look, newer OpenELEC seems to have done nothing for you unfortunately!

Are you running through a proxy server at all? From my research I can see that it could cause that error.

Otherwise, I would suggest cross-grading your OS to LibreELEC. Much better support, releases more often, nightly builds for Kodi 18... Kodi 17 is now at release 17.6 but OpenELEC haven't released an update past 17.3 from what I can see. Several users are using LibreELEC on RPi2/3 with no issue (myself included).  I'm fairly sure you can just drop the tar file into /storage/.update and reboot and it will 'just work'.

**Comment by chchyeah** [comment] 2018-04-16 10:40
Thanks. I wiped the machine and set up LibreELEC. Unfortunately this is still not working. Even the replays now hang and fail to load past the pop up bar.

I lodged a new error: 2601 if anyone has time to look and offer ideas. 

Thanks

**Comment by andybotting** [comment] 2018-04-16 11:25
.. and the mobile app fails for me too.

Definitely a backend issue

**Comment by glennguy** [comment] 2018-04-17 06:59
@chchyeah looks like some progress but as andy said there seems to be an issue on Telstra's side, as it's also failing for me now on 1.8.6. 
Just released 1.8.7, try updating to that and see how you go.

**Comment by chchyeah** [comment] 2018-04-17 09:27
Thanks. 1.8.7 now loads the full bar but now it just hangs on the spinning wheel instead. I guess that is progress but not quite there.

Thanks for the tips though

**Comment by chchyeah** [comment] 2018-04-24 02:26
Hi guys

Just checking in on the off chance someone has had success fixing this?
Thanks

**Comment by glennguy** [comment] 2018-04-24 08:56
Hi @chchyeah

It seems like there's some sort of progress for you with installing LibreELEC.

Can you try playing a video, waiting until it has timed out/spinning circle stops, then submit another issue report/log for us?

**Comment by chchyeah** [comment] 2018-04-25 21:11
Thanks very much. New issue log loaded: 2642

Thanks

**Comment by glennguy** [comment] 2018-04-26 05:05
This is completely untested as I haven't been able to recreate it on my end, but try installing this version attached, confirm you have 1.8.7-0 installed and have another go. If there's still an issue send another log file 
[plugin.video.afl-video.zip](https://github.com/aussieaddons/repo/files/1949765/plugin.video.afl-video.zip)

It looks like for some reason the afl server is dropping the connection unexpectedly. The small changes I made will get it to retry 5 times, waiting 2 seconds inbetween. Fingers crossed!

**Comment by chchyeah** [comment] 2018-04-29 03:09
Thanks very much for this. I installed the update but unfortunately still not working. The blue wheel just spins for a few minutes before showing the error message.

I uploaded a new error log: 2676

Thanks

**Comment by andybotting** [comment] 2018-04-29 22:54
So looking at your log file, I see this:

`Unable to determine if you have any eligible services. Please ensure there is an eligible service linked to your Telstra ID to redeem the free offer. Please visit http://hub.telstra.com.au/sp2017-afl-app for further instructions`

Later I see:

`mis-uuid token must be 32 characters in length, and only contain numbers 0-9 and letters a-f`

I think this suggests you changed your subscription type in the settings.  Can you confirm what sort of subscription type you have?

**Comment by chchyeah** [comment] 2018-04-30 11:04
Thanks - this is weird. My subscription is the free full time pass that comes with Telstra services. I use it every week across both a phone and iPad with no issues. I even confirmed the login details are the same as those typed into the Add On settings. 
In the Add On I selected "free offer, Telstra"

Is there somewhere else I can verify the login details or something in the AddOn as I definitely tyed in the correct details but seems they are not being properly verified.

**Comment by andybotting** [comment] 2018-04-30 11:06
Did you verify it with that url the message gave you?

**Comment by chchyeah** [comment] 2018-04-30 11:09
Yes I did - even checked it now and it shows I have a live pass until Jan 2019.

**Comment by glennguy** [comment] 2018-05-01 10:30
@chchyeah
I have one other idea that if like you to try and rule out what is happening.

If you have wifi on your RPi, can you set up a wifi hotspot on your smartphone and try connecting through that and trying playback again? Just want to rule out your home network/router causing issues.

**Comment by kostaboxon** [comment] 2018-05-07 09:36
Everyone Please NOTE when you log the box into the AFL addon
**DO NOT USE FREE live pass option.** 
Even if you get it for free IT IS A PAID Live Pass Subscription. 
Telstra customers just don't pay for it.
That will be your issue @chchyeah

**Comment by chchyeah** [comment] 2018-05-21 09:10
This fixed it!! 

Thanks for the persistence guys.

**Comment by glennguy** [comment] 2018-05-22 01:42
@chchyeah Great to hear it's finally working!

I don't think the issue is what @kostaboxon asserts though. 

I've observed what looks to be some issues on Telstra's side of things. A couple of weeks back it was impossible to activate a free live pass over wifi on the mobile app, it would come back with an error, and this was mirrored in the addon which would come back with a 502 or 503 (can't remember exactly) error. Strangely though there wasn't an issue in Kodi with accounts that had previously been activated (still wasn't working in the app though), just new ones. Now all of a sudden everything is working fine, thanks Telstra! Although you weren't having this issue (you were logging in fine, just getting the playlist from ooyala was dropping the connection for some reason). Where there's smoke there's fire and whatever problems were happening on their backend could have extended to what you were seeing.

Also note that changing the subscription type in the settings will not have an effect if there is a valid stored login token, you need to clear it first after changing so unless you cleared the token after changing sub type you'd still be running off of the free live pass token.

@kostaboxon With regards to the free vs. paid settings option - I have 2 new Telstra IDs that correctly will **not** authorise when I select the paid method. However on the other 2 existing Telstra IDs that I have, I had previously signed up for the 2 week free trial from afl.com.au, and they authenticate with the paid afl.com.au setting just fine. From this alone I can definitely say that changing to the paid afl.com.au option won't fix all issues like this. Without having access to how things work on Telstra's side I can only speculate, but I don't think that this is intended behavior. Best guess would be that their system is preventing them from removing/deactivating my trial subscription as there's an active free subscription on the same ID and their database doesn't allow for it.

**Comment by frucstuk** [comment] 2019-04-06 08:49
For what its worth it wasnt Telstra Free or PAID Live Pass for me ,it was Widevine DRM. I fixed it after following this guide  https://www.matthuisman.nz/2018/05/kodi-widevine-support.html

**Closed** 2019-04-08 04:42 UTC
